# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Добавьте эту секцию, чтобы предотвратить установку неработающего плагина.
[[plugins]]
  package = "@netlify/plugin-neon"
  # Этот флаг отключает плагин
  [plugins.inputs]
  disabled = true

[dev]
  # Удаляем 'port' и 'target_port'
  # Netlify Dev не будет пытаться проксировать фронтенд
  functions_port = 8888 # Этот порт для функций остается
  publish = "dist"
  functions = "netlify/functions"
  open_browser = false # Предотвратит открытие белого экрана